name: publish to nuget
on:
  push:
    branches:
      - master # Default release branch, may also be named 'master' or 'develop'
jobs:
  test:
    name: get new data
    runs-on: ubuntu-latest
    steps:
      - name: Bump release version
        id: bump_version
        uses: christian-draeger/increment-semantic-version@1.0.2
        with:
          current-version: ${{ steps.previous-tag.outputs.tag }}
          version-fragment: 'bug'
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Publish
      - name: publish on version change
        id: publish_nuget
        uses: rohith/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: Notus.Core/Notus.Core.csproj
          
          VERSION_STATIC: ${{ steps.bump_version.outputs.next-version }}

          NUGET_KEY: ${{secrets.NUGET_API_KEY}}

          NUGET_SOURCE: https://api.nuget.org

